package com.vn.entity;
// Generated Nov 21, 2018 9:37:06 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Records generated by hbm2java
 */
@Entity
@Table(name = "Records")
public class Records  {

	private Long id;
	private Staffs staffs;
	private int type;
	private String reason;
	private Date date;

	public Records() {
		// TODO Auto-generated constructor stub
	}

	
	public Records(Staffs staffs, int type, String reason) {
		this.staffs = staffs;
		this.type = type;
		this.reason = reason;
	
	}
	public Records(Staffs staffs, int type, String reason , Date date) {
		this.staffs = staffs;
		this.type = type;
		this.reason = reason;
		this.date = date;
	
	}

	public Records(Long id, Staffs staffs, int type, String reason, Date date) {
		super();
		this.id = id;
		this.staffs = staffs;
		this.type = type;
		this.reason = reason;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "StaffId", nullable = false)
	public Staffs getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Staffs staffs) {
		this.staffs = staffs;
	}

	@Column(name = "Type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "Reason", nullable = false)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "Date", nullable = false)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}