package com.vn.entity;
// Generated Nov 21, 2018 9:37:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users")
public class Users  {

	private String username;
	private String password;
	private long role;
	private boolean status;

	public Users() {
	}

	public Users(String username, String password, long role, boolean status) {
		this.username = username;
		this.password = password;
		this.role = role;
		this.status = status;
	}

	@Id

	@Column(name = "Username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Role", nullable = false)
	public long getRole() {
		return this.role;
	}

	public void setRole(long role) {
		this.role = role;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}